import { Metadata } from "next"

export const metadata:Metadata = {
  title: 'Home Next Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
         <nav>
         <h1>My Navbar</h1>
          </nav>
        {children}
        </body>
    </html>
  )
}
